info:
  component: Edge Server
  
management:
  endpoint:    restart:      enabled: true
    shutdown:      enabled: true
    health:      enabled: true

zuul:
  routes:
    reporting: 
      path: /reporting/**
      serviceId: reporting-service
    parameter: 
      path: /parameter/**
      serviceId: parameter-service  
    datasource: 
      path: /datasource/**
      serviceId: datasource-service
    preview: 
      path: /preview/**
      serviceId: preview-service           

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG